In [1]:
import pandas as pd
import numpy as np
import json

In [59]:
df = pd.read_json(f"../input_data/persona_hub.json", orient="columns")

In [60]:
df

,persona_id,persona,persona_prompt
85519,85519,a patient who participated in a clinical trial...,"[{'role': 'system', 'content': 'You are a pati..."
126701,126701,an introverted accountant who is extremely det...,"[{'role': 'system', 'content': 'You are an int..."
179838,179838,a graphics programmer who shares and discusses...,"[{'role': 'system', 'content': 'You are a grap..."
108473,108473,a crime novel enthusiast university lecturer w...,"[{'role': 'system', 'content': 'You are a crim..."
160632,160632,a curious and creative high school student who...,"[{'role': 'system', 'content': 'You are a curi..."
...,...,...,...
145625,145625,a biblical scholar and Assyriologist who loves...,"[{'role': 'system', 'content': 'You are a bibl..."
81777,81777,a residential property owner concerned about m...,"[{'role': 'system', 'content': 'You are a resi..."
187017,187017,a history professor hails from Jordan and is i...,"[{'role': 'system', 'content': 'You are a hist..."
142284,142284,a Twitch streamer who regularly purchases merc...,"[{'role': 'system', 'content': 'You are a Twit..."
118017,118017,an event planner with little knowledge about Q...,"[{'role': 'system', 'content': 'You are an eve..."

In [61]:
df = df.rename(columns={"persona_id": "context_id", "persona_prompt": "context"})

In [62]:
df["context_type"] = "persona_hub"

In [63]:
df = df.reset_index(drop=True)

In [64]:
df

,context_id,persona,context,context_type
0,85519,a patient who participated in a clinical trial...,"[{'role': 'system', 'content': 'You are a pati...",persona_hub
1,126701,an introverted accountant who is extremely det...,"[{'role': 'system', 'content': 'You are an int...",persona_hub
2,179838,a graphics programmer who shares and discusses...,"[{'role': 'system', 'content': 'You are a grap...",persona_hub
3,108473,a crime novel enthusiast university lecturer w...,"[{'role': 'system', 'content': 'You are a crim...",persona_hub
4,160632,a curious and creative high school student who...,"[{'role': 'system', 'content': 'You are a curi...",persona_hub
...,...,...,...,...
295,145625,a biblical scholar and Assyriologist who loves...,"[{'role': 'system', 'content': 'You are a bibl...",persona_hub
296,81777,a residential property owner concerned about m...,"[{'role': 'system', 'content': 'You are a resi...",persona_hub
297,187017,a history professor hails from Jordan and is i...,"[{'role': 'system', 'content': 'You are a hist...",persona_hub
298,142284,a Twitch streamer who regularly purchases merc...,"[{'role': 'system', 'content': 'You are a Twit...",persona_hub
299,118017,an event planner with little knowledge about Q...,"[{'role': 'system', 'content': 'You are an eve...",persona_hub

In [65]:
bad_personas = [176389, 79999, 119752, 73719] # personas ids taken from manual check

df.drop(df[df["context_id"].isin(bad_personas)].index, inplace=True)

In [66]:
df.shape[0]

296

In [20]:
df.iloc[6599]["conversation"]

[{'content': 'I got a flower shop and I need to create a post on social media because tommorow is a Valentine day. Please create a list of sentences that I can use',
  'role': 'user'},
 {'content': 'Sure, here are some sentences you can use for your social media post:\n\n1.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n2.   "Create a lasting impression with a Valentine\'s Day flower delivery."\n3.   "Sweep your sweetheart off their feet with a beautiful Valentine\'s Day bouquet."\n4.   "Surprise your loved one with a surprise Valentine\'s Day flower delivery."\n5.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n6.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n7.   "Say "I love you" this Valentine\'s Day with a beautiful bouquet of flowers."\n8.   "Surprise your sweetheart with a Valentine\'s Day flower delivery."\n9.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n10.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n11.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n12.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n13.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n14.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n15.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n16.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n17.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n18.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n19.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n20.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."',
  'role': 'assistant'}]

In [67]:
df.to_json("../input_data/persona_hub.json", orient="columns")